### ISSUE TITLE
Lagging so many balls!!!

### ISSUE THREAD

**Issue by AleksoBre** [Lebroncraft/public#21] opened 2015-03-15 09:55 UTC
I did everything that was written in the .txt file.I also allocated 4 GB of RAM (I have 8GB in total) and i started the game, but it lags a lot. Please help.

**Comment by censink-** [comment] 2015-03-15 13:01
Perhaps the lag is not caused by a RAM shortage, but by an older CPU or GPU?
When exactly does it start lagging?

**Comment by AleksoBre** [comment] 2015-03-15 17:50
I have an Intel core i3 3240 and an AMD Radeon HD 7750. It starts lagging
when I start the map (not the game, but the map) and it won't stop untill I
turn it off. I tried wating for 3 to 4 minutes so the chunks could load,
but it still lagged.

**Comment by censink-** [comment] 2015-03-16 00:06
Your CPU has an integrated GPU (Intel HD Graphics 2500) which isn't very powerful, systems often attempt running games on that integrated GPU, rendering a possible second GPU almost useless. Are you sure it's running on the Radeon?

**Comment by AleksoBre** [comment] 2015-03-16 07:01
I'm not sure, I didn't even know I had another GPU, but I have no problem
running NBA 2K15 on high. If it isn't running on the separate GPU, can I
force it to.

**Comment by AlastairWilkins** [comment] 2015-03-16 15:18
Closing due to the issue being caused by OP's computer specifications. _Therefore not an actual 'issue' as such._

**Closed as completed by AlastairWilkins** 2015-03-16 15:18 UTC
Labels: Section - Minecraft, Cat - Question, Project - CrewMod

**Comment by AleksoBre** [comment] 2015-03-16 20:03
Who's Op?

**Comment by censink-** [comment] 2015-03-17 00:50
http://www.urbandictionary.com/define.php?term=op
The person who created an article, post or in this case, issue

**Comment by AleksoBre** [comment] 2015-03-17 09:29
So that's it, you're not going to help me at all? At least tell me if there
is a way for me to force my separated GPU to work on minecraft, not my
integrated one.

**Comment by censink-** [comment] 2015-03-17 10:46
Sorry i misread your earlier comment, thought you said you were able to do that yourself.

Did some research for you and you should be able to assign applications to your GPU using the Catalyst Control Center. Out of curiosity, what FPS do you get?

**Comment by AleksoBre** [comment] 2015-03-19 13:43
I get 55-60 FPS but every 10 seconds it drops down to 2, and can you show
me how can I assign minecraft to my GPU?

**Comment by AleksoBre** [comment] 2015-03-22 16:36
Can you tell me how to do it?
19.03.2015. 14.43, "aleksa stevancevic" aleksstevancevic@gmail.com је
написао/ла:
