### ISSUE TITLE
Crashing when joining 

### ISSUE THREAD

**Issue by tbone0599** [Lebroncraft/public#72] opened 2015-03-23 01:59 UTC
I downloaded a mod pack and read the installation text. the problem happens when i try to join my own server or even a single player game 

when i join a single player game i get "shutting down internal server" 

when i try to join my own server i just crash......

any suggestions?

**Comment by tbone0599** [comment] 2015-03-23 02:01
This is the crash report 

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2205)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2135)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:239)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2205)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2135)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:239)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 201247136 bytes (191 MB) / 526311424 bytes (501 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 28 mods loaded, 28 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1062-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.3.6} [BuildCraft] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.3.6} [BC Transport] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.3.6} [BC Silicon] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.3.6} [BC Builders] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.3.6} [BC Energy] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.3.6} [BC Factory] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{2.3.5.31} [Chisel 2] (Chisel2-2.3.5.31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LittleBlocks{2.2.4.4} [Little Blocks] (LittleBlocks-2.2.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3345, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by AlastairWilkins** [comment] 2015-03-23 11:29
Duplicate of issue #28

**Closed as completed by AlastairWilkins** 2015-03-23 11:29 UTC
Labels: Mark - Duplicate
