### ISSUE TITLE
i followed all the steps, minecraft detects all mods but when i try creating or loading a world, after a while it says shutting internal servers. please help

### ISSUE THREAD

**Issue by mccreeper** [Lebroncraft/public#24] opened 2015-03-15 22:47 UTC

**Comment by mccreeper** [comment] 2015-03-15 23:02
@censink-

**Comment by censink-** [comment] 2015-03-16 00:10
Dupe of https://github.com/Lebroncraft/public/issues/22

**Closed as completed** 2015-03-16 00:10 UTC
Labels: Mark - Duplicate, Mark - Invalid
